PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS USERS (
  UserID INTEGER PRIMARY KEY AUTOINCREMENT,
  FullName VARCHAR(150) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  Role TEXT NOT NULL DEFAULT 'Contractor' CHECK(Role IN ('Contractor','Beneficiary','Administrator')),
  Status TEXT NOT NULL DEFAULT 'Active' CHECK(Status IN ('Active','Suspended')),
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TENDERS (
  TenderID INTEGER PRIMARY KEY AUTOINCREMENT,
  Title VARCHAR(300) NOT NULL,
  Description TEXT NOT NULL,
  Category TEXT NOT NULL CHECK(Category IN ('Works','Goods','Services')),
  PublishedDate DATE NOT NULL,
  ClosingDate DATETIME NOT NULL,
  Status TEXT NOT NULL DEFAULT 'Draft' CHECK(Status IN ('Draft','Active','Closed')),
  DocPath VARCHAR(500),
  AdminID INTEGER,
  FOREIGN KEY (AdminID) REFERENCES USERS(UserID)
);

CREATE TABLE IF NOT EXISTS SUBMISSIONS (
  SubmissionID INTEGER PRIMARY KEY AUTOINCREMENT,
  UserID INTEGER NOT NULL,
  TenderID INTEGER NOT NULL,
  FilePath VARCHAR(500) NOT NULL,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  Status TEXT NOT NULL DEFAULT 'Received' CHECK(Status IN ('Received','Under Evaluation','Approved','Rejected')),
  UNIQUE(UserID, TenderID),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID),
  FOREIGN KEY (TenderID) REFERENCES TENDERS(TenderID)
);

CREATE TABLE IF NOT EXISTS NEWS (
  NewsID INTEGER PRIMARY KEY AUTOINCREMENT,
  Title VARCHAR(300) NOT NULL,
  Content LONGTEXT NOT NULL,
  ImagePath VARCHAR(500),
  DatePosted DATE NOT NULL,
  AdminID INTEGER,
  FOREIGN KEY (AdminID) REFERENCES USERS(UserID)
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
  LogID INTEGER PRIMARY KEY AUTOINCREMENT,
  EventType VARCHAR(50) NOT NULL,
  UserID INTEGER,
  AffectedRecord INTEGER,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  IPAddress VARCHAR(45),
  FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
